<?php
// pages/scanner.php

$filter_event_id = (int)($_GET['event_id'] ?? 0);

$events = db_query("SELECT id,name FROM events WHERE status='active' ORDER BY event_date ASC");
$recent_scans_sql = "SELECT sl.*,a.full_name,a.email,e.name as event_name
  FROM scan_logs sl
  LEFT JOIN attendees a ON a.id=sl.attendee_id
  LEFT JOIN events e ON e.id=sl.event_id";
$recent_scans_params = [];

if ($filter_event_id) {
    $recent_scans_sql .= " WHERE sl.event_id = ?";
    $recent_scans_params[] = $filter_event_id;
}

$recent_scans_sql .= " ORDER BY sl.scanned_at DESC LIMIT 20";
$recent_scans = db_query($recent_scans_sql, $recent_scans_params);
?>
<div class="page-hero"><h1>QR Code Scanner</h1><p>Scan attendee QR codes for real-time attendance validation.</p></div>

<div class="grid-2 scanner-grid">
  <!-- Left Column: Scanner -->
  <div class="card">
        <div class="card-header" style="justify-content: space-between;">
          <div style="display:flex; align-items:center; gap: 12px;"><span><i class="bi bi-camera-video"></i></span><div class="card-title">Scanner</div></div>
          <form method="GET" action="index.php" class="filter-bar">
              <input type="hidden" name="page" value="scanner">
              <select name="event_id" id="scanner-event-id" class="form-select" style="width:auto;padding:7px 12px;font-size:.8rem;" onchange="this.form.submit()">
                  <option value="">All Events (Recent 20)</option>
                  <?php foreach ($events as $ev): ?>
                      <option value="<?= $ev['id'] ?>" <?= $filter_event_id == $ev['id'] ? 'selected' : '' ?>><?= htmlspecialchars($ev['name']) ?></option>
                  <?php endforeach; ?>
              </select>
              <?php if ($filter_event_id): ?>
                  <a href="index.php?page=scanner" class="btn btn-ghost btn-sm" style="padding: 7px 10px;" title="Clear Filter"><i class="bi bi-x"></i></a>
              <?php endif; ?>
          </form>
        </div>
  
        <div class="scanner-area" id="scanner-area">
          <div class="scanner-viewport" id="scanner-viewport">
            <!-- The QR Code scanner will be rendered here by html5-qrcode -->
          </div>
          <div class="scanner-result" id="scanner-result">
            <p class="text-muted text-sm" style="text-align:center;padding:10px;">
              Camera not active. Click Start Scanner to begin.
              <br><br>
              <span style="font-weight:500;color:var(--text2);">Note:</span> This scanner only works with QR codes generated by the AttendQR system.
            </p>
          </div>
        </div>
  
        <div class="card-footer" style="justify-content: center; flex-wrap: wrap; gap: 10px;">
          <select id="camera-select" class="form-select" style="display:none; width: auto; max-width: 250px;"></select>
          <button class="btn btn-primary" id="scanner-start-btn" style="min-width: 200px;"><i class="bi bi-play-fill"></i> Start Scanner</button>
          <button class="btn btn-ghost" id="scanner-stop-btn" style="display:none; min-width: 200px;"><i class="bi bi-stop-fill"></i> Stop Scanner</button>
        </div>
  </div>

  <!-- Right Column: Scan Log and Manual Lookup -->
  <div>
    <!-- Scan Log Card -->
    <div class="card">
      <div class="card-header">
        <span><i class="bi bi-list-ul"></i></span>
        <div class="card-title">Scan Log</div>
        <span class="badge badge-success"><span class="live-dot" style="margin-right:4px;"></span>Live</span>
      </div>
      <div style="max-height:355px;overflow-y:auto;" id="scan-log">
        <?php if (empty($recent_scans)): ?>
          <div class="empty-state">
            <div class="empty-icon"><i class="bi bi-camera-video"></i></div>
            <div class="empty-text">No scans yet. Start the scanner to see activity.</div>
          </div>
        <?php else: ?>
          <?php foreach ($recent_scans as $s): ?>
          <div class="scan-log-item">
            <span style="font-size:1.4rem;">
              <?= match($s['scan_result']) {
                'checked_in', 'manual_lookup_checked_in'
                    => '<i class="bi bi-check-circle-fill text-success"></i>',
                'already_checked_in', 'manual_lookup_duplicate'
                    => '<i class="bi bi-exclamation-triangle-fill text-warning"></i>',
                'wrong_event', 'manual_lookup_wrong_event'
                    => '<i class="bi bi-exclamation-circle-fill text-error"></i>',
                default // 'invalid', 'not_registered', 'manual_lookup_not_found', 'error'
                    => '<i class="bi bi-x-circle-fill text-error"></i>'
              } ?>
            </span>
            <div style="flex:1;">
              <div style="font-size:.85rem;font-weight:500;color:var(--text);"><?= htmlspecialchars($s['full_name']??'Unknown') ?></div>
              <div style="font-size:.73rem;color:var(--text3);"><?= htmlspecialchars($s['email'] ?? 'No Email') ?> &bull; <?= date('g:i A', strtotime($s['scanned_at'])) ?></div>
            </div>
            <span class="badge <?= match($s['scan_result']){
                'checked_in', 'manual_lookup_checked_in' => 'badge-success',
                'already_checked_in', 'manual_lookup_duplicate' => 'badge-warning',
                default => 'badge-error'
            } ?>">
              <?= match($s['scan_result']){'checked_in'=>'OK','manual_lookup_checked_in'=>'LOOKUP','already_checked_in'=>'DUP','manual_lookup_duplicate'=>'DUP','wrong_event'=>'WRONG','manual_lookup_wrong_event'=>'WRONG',default=>'FAIL'} ?>
            </span>
          </div>
          <?php endforeach; ?>
        <?php endif; ?>
      </div>
    </div>

    <!-- Manual Lookup Card -->
    <div class="card">
      <div class="card-header"><span><i class="bi bi-search"></i></span><div class="card-title">Manual Lookup</div></div>
      <div class="card-body">
        <p class="text-muted text-sm" style="margin-bottom:14px;">Look up an attendee by QR code ID, respondent ID, or email address.</p>
        <div style="display:flex;gap:10px;">
          <input type="text" class="form-input" id="manual-lookup-input" placeholder="QR Code ID, Respondent ID or Email...">
          <button class="btn btn-primary" id="manual-lookup-btn"><i class="bi bi-check-lg"></i> Check</button>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
/* Hide the default UI controls (like the "Stop" button) from the html5-qrcode library.
   We use our own custom buttons in the card footer. */
#scanner-viewport__dashboard_section {
    display: none !important;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', () => {
    // Check if the library is available
    if (typeof Html5Qrcode === 'undefined') {
        console.error('html5-qrcode library is not loaded!');
        return;
    }

    const startBtn = document.getElementById('scanner-start-btn');
    const stopBtn = document.getElementById('scanner-stop-btn');
    const cameraSelect = document.getElementById('camera-select');
    const scannerResultEl = document.getElementById('scanner-result');
    const scannerArea = document.getElementById('scanner-area');
    const scanLogContainer = document.getElementById('scan-log');

    const qrboxFunction = (viewfinderWidth, viewfinderHeight) => {
        let minEdge = Math.min(viewfinderWidth, viewfinderHeight);
        // Use a focused scanning area (80% of the smaller viewport dimension).
        let qrboxSize = Math.floor(minEdge * 0.8);
        return { width: qrboxSize, height: qrboxSize };
    };
    const config = {
        fps: 10,
        qrbox: qrboxFunction,
        experimentalFeatures: { useBarCodeDetectorIfSupported: true } // Enable native scanning for performance
    };

    const html5QrCode = new Html5Qrcode("scanner-viewport");
    let currentCameraId = null;
    let isProcessing = false; // Lock to prevent processing multiple scans at once
    let processingTimeout = null; // To hold the timeout ID for the lock

    // --- Functions ---

    // Sound feedback function (copied from app.js for standalone use on this page)
    function playSound(type = 'success') {
        try {
            const audioContext = new (window.AudioContext || window.webkitAudioContext)();
            if (!audioContext) return;
            const oscillator = audioContext.createOscillator();
            const gainNode = audioContext.createGain();
            oscillator.connect(gainNode);
            gainNode.connect(audioContext.destination);
            gainNode.gain.setValueAtTime(0, audioContext.currentTime);
            gainNode.gain.linearRampToValueAtTime(0.4, audioContext.currentTime + 0.01);
            if (type === 'success') {
                oscillator.type = 'sine';
                oscillator.frequency.setValueAtTime(600, audioContext.currentTime);
                oscillator.frequency.exponentialRampToValueAtTime(900, audioContext.currentTime + 0.05);
            } else {
                oscillator.type = 'square';
                oscillator.frequency.setValueAtTime(220, audioContext.currentTime);
                oscillator.frequency.exponentialRampToValueAtTime(110, audioContext.currentTime + 0.1);
            }
            oscillator.start(audioContext.currentTime);
            gainNode.gain.exponentialRampToValueAtTime(0.00001, audioContext.currentTime + 0.25);
            oscillator.stop(audioContext.currentTime + 0.25);
        } catch (e) {
            console.warn("Could not play sound:", e);
        }
    }

    const onScanSuccess = (decodedText, decodedResult) => {
        if (isProcessing) {
            return; // A scan is already in progress, ignore this one.
        }
        isProcessing = true; // Set the lock

        // processScan is async, so we can use .finally()
        processScan(decodedText).finally(() => {
            // After a cooldown period, release the lock to allow another scan.
            clearTimeout(processingTimeout); // Clear any existing timeout before setting a new one
            processingTimeout = setTimeout(() => {
                isProcessing = false;
                // Only resume if the scanner hasn't been manually stopped in the meantime.
                if (html5QrCode.isScanning) {
                    try {
                        html5QrCode.resume();
                    } catch(e) {
                        console.warn("Could not resume scanner, it might have been stopped already.", e);
                    }
                }
            }, 500); // Cooldown period (reduced from 1500ms for faster scanning)
        });
    };

    const onScanFailure = (error) => {
        // Continuous failure messages can be ignored.
    };

    const startScanner = async () => {
        try {
            const cameras = await Html5Qrcode.getCameras();
            if (cameras && cameras.length) {
                cameraSelect.innerHTML = '';
                cameras.forEach(camera => {
                    const option = document.createElement('option');
                    option.value = camera.id;
                    option.textContent = camera.label || `Camera ${camera.id}`;
                    cameraSelect.appendChild(option);
                });

                startBtn.style.display = 'none';
                stopBtn.style.display = 'inline-flex';
                cameraSelect.style.display = 'inline-block';
                scannerArea.classList.add('scanning');
                scannerResultEl.innerHTML = '<p class="text-muted text-sm text-center">Point QR code at the camera</p>';

                currentCameraId = cameras[0].id;
                await html5QrCode.start(currentCameraId, config, onScanSuccess, onScanFailure);

            } else {
                scannerResultEl.innerHTML = '<p class="text-error text-sm text-center">No cameras found on this device.</p>';
                toast('No cameras found.', 'error');
            }
        } catch (err) {
            console.error('Error starting scanner:', err);
            scannerResultEl.innerHTML = `<p class="text-error text-sm text-center">Error accessing camera: ${err.message}</p>`;
            toast('Could not access camera.', 'error');
        }
    };

    const stopScanner = () => {
        if (html5QrCode.isScanning) {
            html5QrCode.stop().then(() => {
                startBtn.style.display = 'inline-flex';
                stopBtn.style.display = 'none';
                cameraSelect.style.display = 'none';
                scannerArea.classList.remove('scanning', 'success', 'error', 'warning');
                scannerResultEl.innerHTML = '<p class="text-muted text-sm text-center">Camera not active. Click Start Scanner to begin.</p>';
                currentCameraId = null;
                isProcessing = false; // Reset the processing lock
                clearTimeout(processingTimeout); // Clear any pending cooldown timeout
            }).catch(err => console.error('Error stopping scanner:', err));
        }
    };

    const changeCamera = async () => {
        try {
            if (html5QrCode.isScanning) {
                await html5QrCode.stop();
            }
            isProcessing = false; // Reset lock
            clearTimeout(processingTimeout); // Clear cooldown
            currentCameraId = cameraSelect.value;
            await html5QrCode.start(currentCameraId, config, onScanSuccess, onScanFailure);
        } catch (err) {
            console.error('Error changing camera:', err);
            toast('Failed to switch camera. Please try stopping and starting the scanner.', 'error');
            // Attempt to stop scanner completely to reset state
            stopScanner();
        }
    };

    startBtn.addEventListener('click', startScanner);
    stopBtn.addEventListener('click', stopScanner);
    cameraSelect.addEventListener('change', changeCamera);

    // --- AJAX Scan Processing ---
    async function processScan(qrData) {
        const formData = new FormData();
        formData.append('endpoint', 'process_scan');
        formData.append('qr_data', qrData);
        formData.append('event_id', document.getElementById('scanner-event-id').value);
        formData.append('csrf_token', document.querySelector('meta[name="csrf-token"]').getAttribute('content'));

        try {
            const response = await fetch('index.php?page=api', { method: 'POST', body: formData });
            if (!response.ok) throw new Error(`Server returned ${response.status}`);
            const result = await response.json();
            playSound(result.type);
            updateScanResultUI(result);
            updateScanLog(result);
        } catch (e) {
            console.error('Scan processing error:', e);
            playSound('error');
            updateScanResultUI({ type: 'error', status: '❌ Network Error', name: 'Could not connect to server.', event: '—', qr: '', scan_result: 'error' });
        }
    }

    function updateScanResultUI(result) {
        const statusClass = result.type || 'error';
        const statusColorClass = { success: 'text-success', warning: 'text-warning', error: 'text-error' }[statusClass] || 'text-error';
        scannerArea.classList.remove('success', 'error', 'warning');
        scannerArea.classList.add(statusClass);

        scannerResultEl.innerHTML = `
            <div style="display: flex; align-items: center; gap: 16px;">
                <div style="font-size: 2rem;" class="${statusColorClass}">${result.status.split(' ')[0]}</div>
                <div>
                    <div style="font-family:'Poppins',sans-serif;font-weight:700;font-size:1.05rem;" class="${statusColorClass}">${result.status.substring(result.status.indexOf(' ') + 1)}</div>
                    <div style="font-size:.82rem;color:var(--text2);margin-top:3px;">
                        <strong>Name:</strong> ${result.name || 'Unknown'}<br>
                        <strong>Event:</strong> ${result.event || '—'}<br>
                        <strong>QR ID:</strong> ${result.qr || '—'}
                    </div>
                </div>
            </div>`;
        setTimeout(() => scannerArea.classList.remove(statusClass), 2000);
    }

    function updateScanLog(result) {
        const timeString = new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
        const iconMap = { success: '<i class="bi bi-check-circle-fill text-success"></i>', warning: '<i class="bi bi-exclamation-triangle-fill text-warning"></i>', error: '<i class="bi bi-x-circle-fill text-error"></i>' };
        const badgeMap = { success: 'badge-success', warning: 'badge-warning', error: 'badge-error' };
        const badgeTextMap = { 'checked_in': 'OK', 'manual_lookup_checked_in': 'LOOKUP', 'already_checked_in': 'DUP', 'manual_lookup_duplicate': 'DUP', 'wrong_event': 'WRONG', 'manual_lookup_wrong_event': 'WRONG', 'invalid': 'FAIL', 'not_registered': 'FAIL', 'manual_lookup_not_found': 'FAIL' };

        const newLogItem = `
            <div class="scan-log-item">
                <span style="font-size:1.4rem;">${iconMap[result.type] || iconMap['error']}</span>
                <div style="flex:1;">
                    <div style="font-size:.85rem;font-weight:500;color:var(--text);">${result.name || 'Unknown'}</div>
                    <div style="font-size:.73rem;color:var(--text3);">${(result.email || 'No Email')} &bull; ${timeString}</div>
                </div>
                <span class="badge ${badgeMap[result.type] || badgeMap['error']}">${badgeTextMap[result.scan_result] || 'FAIL'}</span>
            </div>`;

        if (scanLogContainer.querySelector('.empty-state')) {
            scanLogContainer.innerHTML = '';
        }
        scanLogContainer.insertAdjacentHTML('afterbegin', newLogItem);
        while (scanLogContainer.children.length > 20) {
            scanLogContainer.lastElementChild.remove();
        }
    }

    // --- Manual Lookup ---
    const lookupInput = document.getElementById('manual-lookup-input');
    const lookupBtn = document.getElementById('manual-lookup-btn');

    async function manualLookup() {
        const query = lookupInput.value.trim();
        if (!query) { toast('Please enter a value to look up.', 'warning'); return; }

        const formData = new FormData();
        formData.append('endpoint', 'manual_lookup');
        formData.append('query', query);
        formData.append('event_id', document.getElementById('scanner-event-id').value);
        formData.append('csrf_token', document.querySelector('meta[name="csrf-token"]').getAttribute('content'));

        try {
            const response = await fetch('index.php?page=api', { method: 'POST', body: formData });
            if (!response.ok) throw new Error(`Server returned ${response.status}`);
            const result = await response.json();
            playSound(result.type);
            updateScanResultUI(result);
            updateScanLog(result);
            lookupInput.value = '';
        } catch (e) {
            console.error('Lookup error:', e);
            playSound('error');
            updateScanResultUI({ type: 'error', status: '❌ Network Error', name: 'Could not connect to server.', event: '—', qr: query, scan_result: 'error' });
        }
    }

    lookupBtn.addEventListener('click', manualLookup);
    lookupInput.addEventListener('keydown', (e) => { if (e.key === 'Enter') manualLookup(); });
});
</script>
